const data = {
    products: [
      {
        _id: 1,
        name: 'productA name',
        category: 'Pharma',
        price: 100,
        token: 'productA name',
        brand: 'Careline',
        description: 'product that has no description',
        countInStock: 6,
        rating: 2.5,
        numReviews: 100,
        image: 'images/P1.jpg',
      },
      {
        _id: 2,
        name: 'productB name',
        category: 'Sports',
        price: 80,
        token: 'productB name',
        brand: 'Sporta',
        description: 'A sporty product',
        countInStock: 0,
        rating: 2.5,
        numReviews: 100,
        image: 'images/p2.jpeg',
      },
      {
        _id: 3,
        name: 'productC name',
        category: 'Pharma',
        price: 19,
        token: 'productC name',
        brand: 'Teva',
        description: 'A mediocare product',
        countInStock: 46,
        rating: 3,
        numReviews: 50,
        image: 'images/p3.jpeg',
      },
      {
        _id: 4,
        name: 'productD name',
        category: 'Food',
        price: 15,
        token: 'productD name',
        brand: 'BestBrand',
        description: 'A very good product',
        countInStock: 315,
        rating: 4.5,
        numReviews: 452,
        image: 'images/p4.jpeg',
      },
      {
        name: 'productE name',
        category: 'Pharma',
        price: 105,
        token: 'productE name',
        brand: 'BestBrand',
        description: 'A very good product',
        countInStock: 0,
        rating: 5,
        numReviews: 1145,
        image: 'images/P1.jpg',
      },
      {
        name: 'productF name',
        category: 'Sports',
        price: 22,
        token: 'productF name',
        brand: 'BestBrand',
        description: 'A very good product',
        countInStock: 547,
        rating: 3,
        numReviews: 7,
        image: 'images/p2.jpeg',
      },
      {
        name: 'productG name',
        category: 'Pharma',
        price: 80,
        token: 'productG name',
        brand: 'BestBrand',
        description: 'A very good product',
        countInStock: 67,
        rating: 4.5,
        numReviews: 101,
        image: 'images/p3.jpeg',
      },
      {
        name: 'productH name',
        category: 'Food',
        price: 152,
        token: 'productH name',
        brand: 'BestBrand',
        description: 'A very good product',
        countInStock: 315,
        rating: 4,
        numReviews: 84,
        image: 'images/p4.jpeg',
      },
    ],
  };
  
  export default data;
  