const data = {
    products: [
      {
        name: 'productA name',
        category: 'Pharma',
        price: 100,
        token: 'productA name',
        brand: 'Careline',
        description: 'product that has no description',
        countInStock: 6,
        rating: 2.5,
        numReviews: 100,
        image: 'images/P1.jpg',
      },
      {
        name: 'productB name',
        category: 'Sports',
        price: 80,
        token: 'productB name',
        brand: 'Sporta',
        description: 'A sporty product',
        countInStock: 6,
        rating: 2.5,
        numReviews: 100,
        image: 'images/p2.jpeg',
      },
      {
        name: 'productC name',
        category: 'Pharma',
        price: 19,
        token: 'productC name',
        brand: 'Teva',
        description: 'A mediocare product',
        countInStock: 46,
        rating: 3,
        numReviews: 50,
        image: 'images/p3.jpeg',
      },
      {
        name: 'productD name',
        category: 'Food',
        price: 15,
        token: 'productD name',
        brand: 'BestBrand',
        description: 'A very good product',
        countInStock: 315,
        rating: 4.5,
        numReviews: 452,
        image: 'images/p4.jpeg',
      },
    ],
  };
  
  export default data;
  